// The ten project destinations, in the order supplied by the client.
// IDs stay stable for the existing /destination/:id QR routes.
import destinationImages from './destination-images.json' with {type: 'json'};
import {visitorDetails, gettingToCalapan, emergencyInformation} from './visitor-details.js';

const tourismDirectory = 'https://www.travelorientalmindoro.ph/directory/tourism-offices';
const cityContact = {
  office: 'Calapan City Tourism Office',
  phone: '0967 233 6074',
  email: 'calapancitytourism@gmail.com',
  address: 'Heritage Building, Culture and Arts Building, Bonifacio Drive, Ibaba East, Calapan City, Oriental Mindoro 5200',
  officeHours: 'The tourism directory lists Monday–Friday, 8:00 AM–5:00 PM. Confirm holidays and office availability before visiting. These are tourism office hours, not destination opening hours.',
  website: tourismDirectory,
};
const source = (title, url) => ({title, url});
const portal = slug => 'https://www.travelorientalmindoro.ph/place/' + slug;
const planningSources = [source('Travel Oriental Mindoro: tourism office contacts', tourismDirectory), source('Travel Oriental Mindoro: getting to Calapan', 'https://www.travelorientalmindoro.ph/page/how-to-get-here')];
const basics = {
  municipality: 'Calapan City',
  province: 'Oriental Mindoro',
  region: 'MIMAROPA',
  latitude: null,
  longitude: null,
  mapNote: 'The map shows Calapan City for orientation. The exact destination pin is awaiting verification; use the named Google Maps search and confirm the entrance with the tourism office.',
  operatingHours: 'Current visitor hours have not been confirmed. Contact the destination or Calapan City Tourism Office before visiting; outdoor visits are best planned in daylight.',
  entranceFee: 'Current admission and activity rates are awaiting confirmation. Ask about entrance, guide, boat, cottage, parking, and other applicable charges before visiting.',
  contactInformation: cityContact,
  rules: ['Use designated public access and follow staff instructions.', 'Keep the destination clean and take your rubbish with you.', 'Respect residents, other visitors, and wildlife.', 'Ask permission before photographing people or entering private areas.'],
  travelTips: ['Confirm access, opening hours, and any fees before leaving.', 'Bring water, sun protection, cash, and a charged phone.', 'Check the weather and arrange your return transport.', 'Support local businesses and respect the community.'],
};
const cityJourney = (destination, landmarks) => ({
  startingPoint: 'Calapan Port or Calapan city center',
  transportation: 'Local tricycle or an arranged vehicle transfer; walking may suit short city-center trips.',
  travelTime: 'The exact journey time depends on your starting point and traffic. Ask your driver before departure.',
  route: 'Calapan Port or city center → ' + destination,
  landmarks,
  publicTransport: 'From outside Mindoro, take a ferry from Batangas Port to Calapan; RORO vessels can carry vehicles. Confirm sailing schedules and fares with the operator. In Calapan, ask a local tricycle driver for the named destination and agree on the fare before boarding.',
  privateVehicle: 'Search for the destination by name and address. Use authorized parking and confirm the entrance locally.',
});
const coastalJourney = destination => ({
  startingPoint: 'Calapan city center; arrange the boat meeting point locally',
  transportation: 'Local land transfer to an agreed coastal departure point, followed by a locally authorized boat.',
  travelTime: 'Boat schedules and trip duration are not confirmed. Your operator must assess the route, tides, and weather.',
  route: 'Calapan city center → operator-confirmed boat departure point → ' + destination,
  landmarks: 'Confirm the departure point and the island landing area with the Calapan City Tourism Office and your boat operator.',
  publicTransport: 'Arrange a local transfer only after the operator confirms the meeting point. There is no verified scheduled passenger service in this guide.',
  privateVehicle: 'Arrange parking at the confirmed departure point and continue by boat. The island is not reachable by a road route.',
});
const marineRules = [
  'Travel only when the boat operator and local authorities permit departure.',
  'Wear a properly fitted life jacket during boat transfers.',
  'Follow the guide and avoid strong currents, deep water, and unauthorized landing areas.',
  'Leave shells, coral, plants, and wildlife undisturbed; take all rubbish back to the mainland.',
];
const marineTips = [
  'Confirm permission to land, boat availability, and the return arrangement before booking.',
  'Bring drinking water, food, sun protection, and a waterproof bag.',
  'Check sea conditions with the operator; allow time for weather-related changes.',
  'Do not assume swimming, snorkeling, food stalls, or toilet facilities are available.',
];

const entries = [
  {
    id: 1, name: 'Sto. Niño Cathedral', slug: 'sto-nino-cathedral', category: 'Faith & heritage',
    description: 'A place of faith in the heart of Calapan. Discover the cathedral and the heritage streets around it.',
    background: "Sto. Niño Cathedral is an active religious landmark in Barangay Ibaba East, at the heart of Calapan City. The provincial tourism portal identifies it as the mother parish of the Apostolic Vicariate of Calapan. Its importance comes from its continuing role in local worship and community life, making it a meaningful introduction to the city's religious heritage.\n\nA visit can include a quiet moment of prayer, a look at the cathedral exterior, and time to read the Church of Calapan historical marker. These are suggested ways to appreciate the place; interior access and photography depend on parish arrangements. Because this is a working church, visitors should plan sightseeing around Mass, parish activities, and the needs of worshippers.\n\nThe surrounding Ibaba East area also connects this stop with Calapan City Plaza and the Oriental Mindoro Heritage Museum. Consider exploring the nearby heritage places together after checking their separate opening times. Contact the parish about current visiting hours, dress respectfully, keep voices low, and ask permission before taking photographs indoors or photographing people.",
    address: 'Ibaba East, Calapan City, Oriental Mindoro, Philippines',
    latitude: 13.41472, longitude: 121.18028,
    mapNote: 'The pin indicates the cathedral area. Confirm the visitor entrance and any access restrictions during church services.',
    directions: cityJourney('Sto. Niño Cathedral, Ibaba East', 'Sto. Niño Cathedral and the nearby Calapan City Plaza.'),
    thingsToDo: ['Spend a quiet moment in prayer when the church is open.', 'View the cathedral exterior and its historical marker.', 'Combine your visit with the nearby City Plaza and Heritage Museum.'],
    attractions: ['Cathedral façade and bell tower', 'Church of Calapan historical marker', 'Ibaba East heritage surroundings'],
    operatingHours: 'Opening and Mass schedules must be confirmed with the parish. Plan sightseeing around services and avoid interrupting worship.',
    entranceFee: 'The provincial tourism portal lists free admission. Donations are voluntary; confirm any charges for special services directly with the parish.',
    bestTimeToVisit: 'Visit during parish-confirmed opening hours. A quiet period outside Mass or other services is better for sightseeing.',
    rules: ['Dress respectfully for an active place of worship.', 'Keep voices low and silence your phone.', 'Ask before taking interior photos; do not photograph worshippers without permission.', 'Keep aisles and entrances clear during services.'],
    contactInformation: {office: 'Sto. Niño Cathedral Parish Office', phone: '(043) 288-9688', website: portal('sto-nino-cathedral')},
    nearbyPlaces: ['Calapan City Plaza', 'Oriental Mindoro Heritage Museum', 'Ibaba East local shops'],
    sources: [source('Provincial tourism: Sto. Niño Cathedral', portal('sto-nino-cathedral')), source('Wikimedia: cathedral location and photographs', 'https://commons.wikimedia.org/wiki/Category:Calapan_Cathedral')],
  },
  {
    id: 2, name: 'Silonay Mangrove Conservation Eco-Park', slug: 'silonay-mangrove-conservation-eco-park', category: 'Nature & conservation',
    description: 'Follow the mangrove boardwalk and discover a quieter side of Calapan’s coastal environment.',
    background: "Silonay Mangrove Conservation Eco-Park is a coastal nature destination in Barangay Silonay, Calapan City. The provincial tourism portal describes a 42-hectare mangrove area with a 350-meter boardwalk leading to a six-meter viewing tower. From permitted viewing areas, visitors can appreciate the relationship between the mangrove habitat, Silonay River, and the adjacent sea.\n\nIts biodiversity is part of the park's story. A 2014 survey cited by the portal recorded 15 mangrove species and 29 bird species, including seven endemic to the Philippines. These are historical survey findings rather than a guarantee of what visitors will see on a particular day. Quiet observation and community-guided interpretation offer a thoughtful way to explore the setting.\n\nPlan the experience around a boardwalk visit, birdwatching, and learning about local conservation, subject to current access. Ask park staff whether the tower and boardwalk are open, whether a guide can accompany your group, and how tides or weather affect the visit. Stay on permitted paths, avoid disturbing wildlife, bring water, and arrange your return transport before starting the walk.",
    address: 'Barangay Silonay, Calapan City, Oriental Mindoro, Philippines',
    latitude: 13.40094506, longitude: 121.2251015,
    mapNote: 'The pin follows the conservation park location published by Travel Oriental Mindoro. Confirm the visitor entrance and current boardwalk access with park staff.',
    directions: cityJourney('Silonay Mangrove Conservation Eco-Park, Barangay Silonay', 'Barangay Silonay and the conservation park entrance; confirm the boardwalk access locally.'),
    thingsToDo: ['Walk the boardwalk when open to visitors.', 'Observe birds quietly from permitted viewing areas.', 'Learn about mangrove protection from community guides.'],
    attractions: ['350-meter mangrove boardwalk', 'Six-meter viewing tower, subject to access', 'Silonay River, coastal habitat, and birdlife'],
    entranceFee: 'Travel Oriental Mindoro lists free admission. Confirm current guide, activity, and other service charges with park staff before visiting.',
    bestTimeToVisit: 'Choose a daylight visit in fair weather. Ask the community guide about tide conditions, boardwalk access, and good birdwatching times.',
    rules: ['Stay on the boardwalk and follow capacity or access limits.', 'Do not cut mangroves, collect wildlife, or feed birds.', 'Keep noise low and dispose of no rubbish in the water.', 'Use the observation tower only when staff allow access.'],
    contactInformation: {office: 'Silonay Mangrove Conservation Eco-Park', phone: '0920 287 5330', website: portal('silonay-mangrove-conservation-eco-park')},
    nearbyPlaces: ['Suqui Beach', 'Calapan Zoological and Recreational Park', 'Calapan city center'],
    sources: [source('Provincial tourism: Silonay Mangrove Conservation Eco-Park', portal('silonay-mangrove-conservation-eco-park'))],
  },
  {
    id: 3, name: 'Oriental Mindoro Heritage Museum', slug: 'oriental-mindoro-heritage-museum', category: 'Culture & heritage',
    description: 'Get to know Mindoro through its people, landscapes, and cultural stories at the old provincial capitol.',
    background: "The Oriental Mindoro Heritage Museum introduces the province through its cultural and natural identity. It occupies the Old Provincial Capitol site in Barangay Ibaba East, Calapan City, where the Cal-kuta Spanish fortress heritage area is located. The provincial tourism portal describes a combination of classic and modern design inspired by the MAHAL TANA theme.\n\nThe theme brings together Mangyan, Halcon, Tamaraw, and Naujan Lake as symbols of Oriental Mindoro. Visitors can use these themes as a starting point for understanding how communities and landscapes contribute to the province's identity. Take time to read the available interpretation and ask staff about the displays, rather than treating the visit only as a photo stop. Exhibition access and guided interpretation should be confirmed directly with the museum.\n\nThis museum is distinct from the Calapan City Museum at City Hall, so give your driver the Old Provincial Capitol address in Ibaba East. It can be considered alongside the nearby cathedral and City Plaza when planning a heritage visit. Confirm the current opening schedule, group arrangements, accessibility, and photography rules before travelling, especially for school visits or larger parties.",
    address: 'Old Provincial Capitol, Barangay Ibaba East, Calapan City, Oriental Mindoro, Philippines',
    latitude: 13.41496409, longitude: 121.1801701,
    mapNote: 'The pin follows the Ibaba East Heritage Museum listing on Travel Oriental Mindoro, near the Old Provincial Capitol and Cal-kuta site. Confirm the visitor entrance locally.',
    directions: cityJourney('Oriental Mindoro Heritage Museum, Old Provincial Capitol, Ibaba East', 'The old provincial capitol and Cal-kuta heritage area; not the New Calapan City Hall.'),
    thingsToDo: ['Explore the exhibits when the museum is open.', 'Learn about Mindoro’s communities and natural heritage.', 'Ask museum staff about guided interpretation and group visits.'],
    attractions: ['MAHAL TANA themed heritage exhibitions', 'Old Provincial Capitol setting', 'Cal-kuta Spanish fortress heritage area'],
    operatingHours: 'A March 2026 tourism advisory reported Tuesday–Sunday, 7:00 AM–6:00 PM. This was an adjusted schedule; confirm the current hours and booking arrangements with the Provincial Tourism Office.',
    entranceFee: 'The provincial tourism portal lists free admission. Confirm current entry and group-visit arrangements with museum staff.',
    bestTimeToVisit: 'Visit during confirmed opening hours and allow time to read the displays. Contact the museum before arranging a school or group visit.',
    rules: ['Follow staff instructions about photography and exhibit access.', 'Do not touch displays unless they are marked interactive.', 'Keep food and drinks outside exhibition areas.', 'Treat cultural objects and community stories respectfully.'],
    contactInformation: {office: 'Oriental Mindoro Heritage Museum', email: 'orientalmindoroheritagemuseum@gmail.com', website: portal('oriental-mindoro-heritage-museum')},
    nearbyPlaces: ['Sto. Niño Cathedral', 'Calapan City Plaza', 'Ibaba East heritage streets'],
    sources: [source('Provincial tourism: Oriental Mindoro Heritage Museum', portal('oriental-mindoro-heritage-museum')), source('March 2026 tourism schedule advisory', 'https://newsinfo.inquirer.net/2193291/oriental-mindoro-tourism-offices-adopt-new-4-day-workweek-hours/amp')],
  },
  {
    id: 4, name: 'Calapan Zoological and Recreational Park', slug: 'calapan-zoological-and-recreational-park', category: 'Parks & recreation',
    description: 'A green pause in Barangay Bulusan, with shaded surroundings and spaces for a relaxed local outing.',
    background: "Calapan Zoological and Recreational Park is also known as Calapan Nature Park or Bulusan Park. Located in Barangay Bulusan, it offers a tree-shaded setting for a local outdoor outing. The provincial tourism portal describes recreational spaces, picnic and camping grounds, a mini-zoo, and wall-climbing facilities, although visitors must confirm which areas are currently operating.\n\nThe park is also described as the starting point of the Bulusan eco-trail toward the seashore in Barangay Parang. Its published activities include walking, jogging, trekking, cycling, and camping. These descriptions introduce the park's recreation potential; they do not establish that every activity is available without a reservation, guide, or additional permission. Ask staff which route or activity suits your group before setting out.\n\nFor a relaxed visit, consider permitted shaded paths and an arranged picnic. Families should keep children close around animal enclosures and recreation areas, and visitors should never feed or disturb animals. Confirm toilets, food arrangements, equipment, group capacity, and any facility charges with management. Bring drinking water and suitable footwear, and arrange a return pickup if planning a longer stay.",
    address: 'Barangay Bulusan, Calapan City, Oriental Mindoro, Philippines',
    latitude: 13.40496178, longitude: 121.1991656,
    mapNote: 'The pin follows the Calapan Nature Park location published by Travel Oriental Mindoro. Ask locally for the Bulusan Park visitor entrance.',
    directions: cityJourney('Calapan Zoological and Recreational Park, Bulusan', 'Bulusan Park / Calapan Nature Park and the designated visitor entrance.'),
    thingsToDo: ['Walk or jog through permitted shaded paths.', 'Enjoy a picnic or arrange camping with park management.', 'View the mini-zoo where staff allow access.', 'Ask staff about guided access to the Bulusan eco-trail, cycling, and climbing facilities.'],
    attractions: ['Tree-shaded picnic and camping grounds', 'Mini-zoo and wall-climbing facilities, subject to current access', 'Bulusan eco-trail toward Barangay Parang'],
    entranceFee: 'Travel Oriental Mindoro lists free admission under Calapan Nature Park. Confirm current picnic-area, pavilion, camping, and activity charges with park management.',
    bestTimeToVisit: 'A fair-weather morning or cooler afternoon suits an outdoor visit. Confirm the park’s current opening time and any temporary closures.',
    rules: ['Do not feed, tease, or touch animals.', 'Respect barriers and restricted areas.', 'Supervise children near animals and recreation facilities.', 'Use picnic and gathering spaces only as permitted by staff.'],
    contactInformation: {office: 'Calapan Nature Park / Bulusan Park', phone: '(043) 288-3883', website: portal('calapan-nature-park')},
    nearbyPlaces: ['Suqui Beach', 'Silonay Mangrove Conservation Eco-Park', 'Calapan city center'],
    sources: [source('Provincial tourism: Calapan Nature Park', portal('calapan-nature-park')), source('PSA: Bulusan recreational and zoological park location', 'https://rssomimaropa.psa.gov.ph/system/files/attachment-dir/City%20of%20Calapan%20Spearheads%20Kasalang%20Bayan%202025.pdf')],
  },
  {
    id: 5, name: 'Plaza del Gobernador', slug: 'plaza-del-gobernador', category: 'Parks & city life',
    description: 'A welcoming public space in Camilmil, known for its fountain, community gatherings, and local evenings.',
    background: "Plaza del Gobernador, also called Ang Liwasan ng Mamamayan, is a provincial public space on Governor Ignacio Street in Barangay Camilmil, Calapan City. The provincial tourism portal highlights its dancing fountain, seating, playground, and food or souvenir stalls. It offers a setting for a city outing built around public space and local community life.\n\nA visit may include walking around accessible areas, spending time with family, and watching a fountain presentation when one is scheduled. The plaza's general access and the fountain programme should be treated as separate arrangements. Published descriptions and earlier show advisories introduce what the place is known for; they do not guarantee a performance on your intended date. Ask the administration about current shows, events, and operating stalls.\n\nThis destination is different from Calapan City Plaza in Ibaba East. Give your driver the Camilmil address to avoid confusion. For an evening outing, confirm the return pickup and allow time to find your meeting point after the show. Supervise children near the playground, keep clear of the fountain basin, and check current toilet, parking, and accessibility arrangements before visiting.",
    address: 'Governor Ignacio Street, Barangay Camilmil, Calapan City, Oriental Mindoro, Philippines',
    latitude: 13.40518677, longitude: 121.1769897,
    mapNote: 'The pin follows the Plaza del Gobernador location published by Travel Oriental Mindoro. Fountain show times and any event entrances should be confirmed locally.',
    directions: cityJourney('Plaza del Gobernador, Governor Ignacio Street, Camilmil', 'The Provincial Capitol area and Plaza del Gobernador; this is separate from Calapan City Plaza in Ibaba East.'),
    thingsToDo: ['Take a relaxed walk through the permitted public areas.', 'Watch the dancing fountain when a show is scheduled.', 'Visit open local food and souvenir stalls.'],
    attractions: ['Dancing fountain', 'Public seating and gathering spaces', 'Playground and local stalls, subject to availability'],
    operatingHours: 'Confirm current plaza access hours locally. A March 2026 advisory reported fountain shows Tuesday–Sunday, 7:00–7:30 PM, beginning March 17; verify the show schedule before planning an evening visit.',
    entranceFee: 'The provincial tourism portal lists free admission to the plaza. Food, merchandise, and any separately managed services are paid for individually.',
    bestTimeToVisit: 'A cooler late afternoon suits a walk. For the fountain, confirm the evening show schedule and weather before leaving.',
    rules: ['Do not enter the fountain or climb its fixtures.', 'Supervise children around water and the playground.', 'Keep walkways clear and use designated rubbish bins.', 'Follow event, security, and stall-area instructions.'],
    contactInformation: {office: 'Plaza del Gobernador', phone: '0967 082 9736', email: 'plazadelgobernador@gmail.com', website: portal('plaza-del-gobernador-:-ang-liwasan-ng-mamamayan')},
    nearbyPlaces: ['Oriental Mindoro Provincial Capitol area', 'Camilmil shops and eateries', 'Calapan city center'],
    sources: [source('Provincial tourism: Plaza del Gobernador', portal('plaza-del-gobernador-:-ang-liwasan-ng-mamamayan')), source('March 2026 fountain schedule advisory', 'https://newsinfo.inquirer.net/2193291/oriental-mindoro-tourism-offices-adopt-new-4-day-workweek-hours/amp')],
  },
  {
    id: 6, name: 'Calapan City Plaza', slug: 'calapan-city-plaza', category: 'Parks & heritage',
    description: 'Pause in Calapan’s civic heart, where monuments and everyday community life share a familiar meeting place.',
    background: "Calapan City Plaza is a public gathering space in the Ibaba East city-center area, near Sto. Niño Cathedral. Its monuments, Mindoro relief map, and pavilion connect a visitor's city walk with local civic and community life. The city government has also identified the City Plaza pavilion as a venue for public events, although activities vary by date.\n\nThe plaza can be appreciated as a place to pause between nearby heritage stops. Walk through permitted areas, look at the monuments and relief display, and observe how the space is used by the community. When an event is underway, visitor movement, seating, or access to the pavilion may follow temporary arrangements. Respect those instructions and leave public paths clear.\n\nThe cathedral and Oriental Mindoro Heritage Museum offer possible companion stops for a city heritage visit, with their own schedules and visitor rules. Calapan City Plaza should not be confused with Plaza del Gobernador in Camilmil. Confirm the correct destination with your driver, check safe pedestrian crossings, and ask locally about toilets, parking, seating, and current event restrictions. Bring water and sun protection for an outdoor visit.",
    address: 'Calapan City Plaza, Ibaba East city-center area, Calapan City, Oriental Mindoro, Philippines',
    latitude: 13.41463, longitude: 121.17921,
    mapNote: 'The pin marks the City Plaza area on OpenStreetMap. Confirm the event entrance and any temporary access restrictions locally.',
    directions: cityJourney('Calapan City Plaza, Ibaba East city-center area', 'Sto. Niño Cathedral, the City Plaza monuments, and the pavilion.'),
    thingsToDo: ['Walk around the accessible plaza paths.', 'View the monuments and the Mindoro relief map.', 'Explore the nearby cathedral and heritage museum.'],
    attractions: ['City Plaza monuments', 'Mindoro relief map', 'Community pavilion and gathering space'],
    entranceFee: 'Current access and event charges have not been independently confirmed. Ask locally; a special event or reserved pavilion may have separate arrangements.',
    bestTimeToVisit: 'A cooler morning or late afternoon suits a walk. Check the local event calendar if you want to visit a community activity.',
    rules: ['Do not climb monuments or damage public displays.', 'Keep paths clear during events and gatherings.', 'Use public seating considerately and keep the plaza clean.', 'Follow security and event-management instructions.'],
    nearbyPlaces: ['Sto. Niño Cathedral', 'Oriental Mindoro Heritage Museum', 'Calapan public-market area'],
    sources: [source('Calapan City Government: City Plaza pavilion', 'https://cityofcalapan.gov.ph/2025/12/01/miss-calapan-city-2025-presentation-of-candidates/'), source('City Plaza photographs and monuments', 'https://commons.wikimedia.org/wiki/Category:Calapan_Plaza'), source('OpenStreetMap: City Plaza', 'https://www.openstreetmap.org/way/654388807')],
  },
  {
    id: 7, name: 'Aganagahaw Islet', slug: 'aganhao-islet', category: 'Islands & coast',
    description: 'A small offshore escape near Silonay Island, described for its white-sand strip, rocky edges, and open sea views.',
    background: "Aganagahaw Islet is a small offshore destination near Silonay Island on Calapan's eastern coast. A historical Calapan tourism guide describes a narrow white-sand strip used for local excursions. A September 2014 visitor account adds descriptions of rocky formations at the beach edges and boat approaches from Suqui or Lazareto. These older accounts provide background, rather than current confirmation of access or services.\n\nThe setting can be appreciated through its shoreline, rocky edges, wooded scenery, and views across the surrounding coast. An operator-arranged visit may include coastal photography, a permitted beach walk, or a small picnic after landing permission is obtained. Nearby Harka Piloto Fish Sanctuary requires its own access arrangements and should not be assumed to be included in an islet trip.\n\nPlan this visit with a locally authorized boat operator and an agreed mainland meeting point. Confirm the route, landing permission, passenger capacity, round-trip cost, and return time before departure. Current toilets, food, shelter, and water activities are not verified. Bring supplies, follow the operator's weather assessment, wear a life jacket during transfers, and take all rubbish back to the mainland.",
    address: 'Aganagahaw Islet, near Silonay Island, offshore eastern Calapan City, Oriental Mindoro, Philippines; confirm the departure and landing point with a local operator',
    directions: {
      ...coastalJourney('Aganagahaw Islet'),
      startingPoint: 'Calapan Port or city center, followed by an operator-confirmed coastal meeting point',
      transportation: 'Tricycle or arranged land transfer, then a hired motorized boat with an authorized local operator.',
      route: 'Calapan Port / city center → confirmed Suqui or Lazareto meeting point → Aganagahaw Islet',
      landmarks: 'Older visitor accounts name Suqui and Lazareto as boat approaches. Confirm which departure and landing points are permitted for your trip.',
      publicTransport: 'Reach Calapan by ferry from Batangas if traveling from outside Mindoro. Arrange the boat first, then ask a local tricycle driver for the agreed coastal meeting point. No scheduled passenger service to the islet is confirmed.',
      privateVehicle: 'Drive only to the operator-confirmed mainland meeting point, arrange parking there, and continue by boat. Confirm the return pickup before departure.',
    },
    directionsQuery: 'Calapan City Tourism Office, Calapan City, Oriental Mindoro',
    thingsToDo: ['Take an operator-arranged boat trip to view the islet and surrounding coast.', 'Walk the accessible beach strip after landing permission is confirmed.', 'Enjoy a small picnic in a permitted area and bring all rubbish back to the mainland.', 'Photograph the rocky shore and views toward nearby islands.', 'Ask the tourism office about a separately permitted visit to nearby Harka Piloto Fish Sanctuary.'],
    attractions: ['Small white-sand beach described in historical tourism accounts', 'Boulders and rocky formations at the shoreline', 'Views toward Silonay Island and the eastern Calapan coast', 'Nearby Harka Piloto Fish Sanctuary, with separate access arrangements'],
    operatingHours: 'Visits are arranged with a boat operator rather than a confirmed public timetable. Plan a daylight outing and agree on departure, landing, and return times before leaving the mainland.',
    entranceFee: 'A current entrance tariff is not confirmed. Request a quote covering the round-trip boat, guide, any landing or conservation fees, and waiting time. Historical boat prices are not used as current rates.',
    bestTimeToVisit: 'Choose a fair-weather daylight trip when the operator confirms safe sea and landing conditions. Ask how tides affect the beach strip and leave enough time for the return crossing before dark.',
    rules: marineRules,
    travelTips: ['Save the boat operator’s number and agree on a return pickup or waiting arrangement.', 'Bring your own drinking water, food, sun protection, and a waterproof bag; facilities are not confirmed.', 'Wear footwear suitable for sand and rocky landings, and follow the guide’s chosen access route.', 'Do not assume a quiet-looking beach is safe for swimming; ask about currents and permitted water activities.', 'Take a charged phone and bring all rubbish back to the mainland.'],
    nearbyPlaces: ['Silonay Island / Harka Piloto Fish Sanctuary', 'Silonay Mangrove Conservation Eco-Park on the mainland', 'Suqui and Lazareto coastal communities'],
    sources: [source('Historical Calapan tourism guide: Aganagahaw and nearby islands', 'https://www.vigattintourism.com/tourism/articles/Welcome-to-Calapan-City'), source('Aganagahaw visitor account — historical description, September 2014', 'https://www.tripadvisor.com.ph/Attraction_Review-g298447-d2101057-Reviews-Aganhao_Island-Calapan_Oriental_Mindoro_Province_Mindoro.html'), source('Department of Tourism: nearby Harka Piloto Fish Sanctuary', 'https://www.tourism.gov.ph/explore/harka-piloto-fish-sanctuary/')],
  },
  {
    id: 8, name: 'Caluangan Lake', slug: 'caluangan-lake', category: 'Lakes & nature',
    description: 'Explore Calapan’s quieter lake landscape, shaped by fishing communities, river connections, and community tourism.',
    background: "Caluangan Lake, also historically labelled Baruyan Lake, is part of western Calapan's waterside landscape and fishing livelihoods. Shoreline references include Wawa, Baruyan, Canubing, Tawagan, and Masipit. Understanding the lake involves its surrounding communities and river connections as well as the view from the water. A visitor should arrange a specific, permitted lakeshore access point rather than treating the map reference as an entrance.\n\nIn September 2022, the Philippine Information Agency reported three SMARTT community floating cottages in Barangay Tawagan for excursions around the lake and neighbouring rivers. Another 2022 report documented shoreline bamboo planting, while a February 2026 city update described oyster-culture pilot-testing plans. These dated reports illustrate community tourism and livelihood initiatives; they do not confirm that every project or cottage is operating today.\n\nAsk the tourism office to connect you with a currently operating community host. A confirmed visit may offer lakeside photography, guided observation, and opportunities to learn about local livelihoods. Agree on permitted activities, boat or cottage availability, food arrangements, capacity, and the full cost before booking. Respect private fishponds and access paths, use a life jacket for boat activities, and arrange the land transfer home.",
    address: 'Caluangan Lake, western Calapan City, Oriental Mindoro, Philippines; shoreline communities include Wawa, Baruyan, Canubing, Tawagan, and Masipit',
    latitude: 13.36167, longitude: 121.14,
    mapNote: 'The pin is an approximate lake reference based on a NAMRIA chart correction, not a visitor entrance or boat launch. Confirm a permitted shore access point locally.',
    directions: {
      ...cityJourney('an authorized Caluangan Lake access point', 'Wawa, Baruyan, and Tawagan lakeside communities; the SMARTT floating-cottage project was reported in Tawagan.'),
      startingPoint: 'Calapan Port or city center; arrange the lakeside meeting point before traveling',
      transportation: 'Tricycle or an arranged vehicle to the confirmed community access point; a boat or floating-cottage trip requires a separate operator booking.',
      route: 'Calapan Port / city center → confirmed Wawa, Baruyan, or Tawagan access point → permitted lakeside visit or booked lake trip',
      publicTransport: 'Ask the tourism office which lakeside community is receiving visitors. Give the tricycle driver the specific operator or meeting point, rather than the lake’s reference pin.',
      privateVehicle: 'Use the operator’s agreed land address for navigation and confirm parking. The lake-center map pin is not a road entrance or a boat launch.',
    },
    directionsQuery: 'Calapan City Tourism Office, Calapan City, Oriental Mindoro',
    thingsToDo: ['Ask about a locally operated lake or river cruise and confirm availability before booking.', 'Inquire about the SMARTT floating cottages in Tawagan, first reported open in 2022.', 'Enjoy landscape photography and quiet bird observation from permitted areas.', 'Learn from local guides about fishing livelihoods and shoreline conservation.', 'If a floating-cottage trip is available, ask the operator about bringing food for a small group outing.'],
    attractions: ['Lake landscape and connections to surrounding rivers', 'SMARTT community floating-cottage project in Tawagan; current operations require confirmation', 'Fishing-community scenery and local livelihoods', 'Shoreline bamboo-planting and conservation initiatives'],
    operatingHours: 'There is no confirmed lake-wide visitor schedule. Shore access and community tours depend on the chosen operator. Book a daylight visit and confirm departure, trip duration, and the return time.',
    entranceFee: 'No current lake-wide entrance or tour tariff is confirmed. Ask for the boat or floating-cottage rental price, group capacity, guide fee, and any food, parking, or other charges. Confirm whether the quote is per person or per group.',
    bestTimeToVisit: 'A cooler morning or late afternoon can suit lakeside viewing. Choose daylight and fair weather, then ask the operator about water levels, wind, and tour conditions before departing.',
    rules: ['Respect private fishponds, fish cages, and working fishing areas.', 'Wear a life jacket for boat transfers and follow the operator’s passenger limit.', 'Do not swim or enter the water without authorized local guidance.', 'Avoid disturbing birds and shoreline vegetation; keep noise low.', 'Keep the lake clean and use only permitted access paths.'],
    travelTips: ['Confirm that the community operator is currently receiving visitors before traveling to the shore.', 'Ask for a clear meeting-point address, parking instructions, and a round-trip arrangement.', 'For group trips, confirm capacity and food arrangements directly with the operator.', 'Bring water, sun protection, insect repellent, cash, and a waterproof pouch.', 'Allow time for weather changes and respect the lake’s role as a working fishing area.'],
    nearbyPlaces: ['Tawagan lakeside community', 'Wawa lakeside community', 'Baruyan community and river area'],
    sources: [source('PIA: SMARTT floating cottages in Tawagan, September 2022', 'https://mirror.pia.gov.ph/news/2022/09/28/3-smartt-floating-cottages-pinasinayaan-at-binuksan-na-sa-publiko'), source('PIA: Caluangan Lake shoreline communities and conservation', 'https://mirror.pia.gov.ph/news/2022/10/10/calapan-lgu-conducts-bamboo-planting-at-caluangan-lake'), source('Calapan City Government: aquaculture plans, February 2026', 'https://cityofcalapan.gov.ph/2026/02/06/strengthening-sustainable-aquaculture-in-calapan-city/'), source('NAMRIA: Lake Caluangan chart-name correction, September 2025', 'https://www.namria.gov.ph/jdownloads/Notice%20to%20Mariners/09_September_2025_Edition.pdf')],
  },
  {
    id: 9, name: 'Baco Islands', slug: 'baco-island', category: 'Islands & coast',
    description: 'Wooded island silhouettes off northern Mindoro, best explored with a locally arranged and permitted boat visit.',
    background: "The Baco Islands form an island group off northern Mindoro. Calapan's published history identifies the Baco islets within the city's jurisdiction. Baco Grande, Baco Medio, and Baco Chico are distinct parts of this offshore landscape, so visitors should be clear about which island or viewing route a proposed boat excursion includes.\n\nThe gallery introduces the wooded island group and its appearance from the sea. A planned excursion can focus on offshore scenery and coastal photography, subject to an operator-confirmed route. An island photograph or map reference does not establish public landing access, a developed beach facility, or a regularly operating visitor service. Ask whether your trip is a viewing cruise or includes a separately permitted landing.\n\nCoordinate the departure point, route, boat capacity, permissions, and round-trip arrangements with a local operator and the tourism office. Confirm food, water, toilets, shelter, and any charges before committing to a visit. Plan around daylight and approved sea conditions, wear a life jacket during transfers, and agree on the mainland return time. Keep wildlife and vegetation undisturbed and bring rubbish back with you.",
    address: 'Baco Islands (Baco Grande, Baco Medio and Baco Chico), offshore northern Mindoro, Calapan City, Oriental Mindoro, Philippines; confirm the departure point locally',
    latitude: 13.46721, longitude: 121.16022,
    mapNote: 'The pin is an island reference, not a boat departure point or a confirmed landing site. Arrange an authorized operator and mainland meeting point before travel.',
    directions: coastalJourney('Baco Islands'),
    operatingHours: 'Visits depend on an arranged boat trip and confirmed access, rather than a published walk-in schedule. Plan a daylight departure and return, subject to the operator?s weather assessment and any landing permissions.',
    directionsQuery: 'Calapan City Tourism Office, Calapan City, Oriental Mindoro',
    thingsToDo: ['Ask the tourism office about permitted boat excursions.', 'View the wooded island group from the sea.', 'Photograph coastal scenery on an operator-approved trip.'],
    attractions: ['Baco island-group silhouettes', 'Wooded offshore landscape', 'Northern Mindoro sea views'],
    bestTimeToVisit: 'Choose an operator-approved daylight trip with calm sea conditions. Confirm permissions, the departure point, and the return journey first.',
    rules: marineRules,
    travelTips: marineTips,
    nearbyPlaces: ['Baco Medio and Baco Chico island areas', 'Calapan mainland coast', 'Calapan city center'],
    sources: [source('Provincial tourism: Calapan history and Baco islets', 'https://www.travelorientalmindoro.ph/municipality/calapan-city/history'), source('Wikidata: Baco Grande Island', 'https://www.wikidata.org/wiki/Q31473507'), source('Baco island-group photograph and description', 'https://commons.wikimedia.org/wiki/File:Baco_Islands.JPG')],
  },
  {
    id: 10, name: 'Suqui Beach', slug: 'suqui-beach', category: 'Beaches & coast',
    description: 'A local gray-to-black-sand coastal stop in Barangay Suqui, suited to a relaxed shore visit and sea-view photography.',
    background: "Suqui Beach is a coastal destination in Barangay Suqui on Calapan's eastern side. Historical tourism descriptions place it along the Lazareto–Suqui–Parang gray-sand coast, while older visitor accounts describe darker sand and local picnic outings. The provincial government's record of an Earth Day coastal clean-up also connects the shoreline with community care for the coastal environment.\n\nThe name can refer to the barangay shoreline as well as privately managed beachfront properties. A shore walk, coastal photography, or an arranged picnic can be considered once you have confirmed a suitable access point. Facilities and visitor arrangements differ between establishments. Gallery photographs show particular views and earlier appearances; they do not confirm public entry, current resort operation, or today's prices.\n\nBefore travelling, choose a specific public entrance or operating beachfront establishment and confirm admission, cottage rental, toilets, shade, food, and parking. Ask locally about water conditions, swimming restrictions, and lifeguard availability rather than assuming the beach is suitable for swimming. Bring water, sun protection, and footwear for the shore, supervise children, and arrange a return pickup while allowing enough daylight for the journey back.",
    address: 'Barangay Suqui coastal area, Calapan City, Oriental Mindoro, Philippines',
    directions: {
      ...cityJourney('Suqui Beach, Barangay Suqui', 'Barangay Suqui and your confirmed public access point or beachfront establishment.'),
      transportation: 'Local tricycle or an arranged vehicle transfer from Calapan Port or the city center.',
      route: 'Calapan Port / city center → Barangay Suqui → confirmed beachfront entrance',
      publicTransport: 'Reach Calapan by ferry from Batangas if needed, then ask a local tricycle driver for Barangay Suqui and the specific beach entrance. Agree on the fare and return pickup before boarding.',
      privateVehicle: 'Search for Suqui Beach or your chosen beachfront establishment in Barangay Suqui. Confirm that its entrance and parking are available to visitors; respect private access roads.',
    },
    thingsToDo: ['Take a relaxed shoreline walk along accessible sections when tides and conditions permit.', 'Photograph the darker sand, sea views, and everyday coastal scenery.', 'Arrange a small picnic at a confirmed public area or an operating beachfront establishment.', 'Ask a local operator about permitted offshore excursions; availability and departure points vary.', 'Join a coastal clean-up if the barangay or tourism office has an announced activity.'],
    attractions: ['Gray-to-black-sand shoreline described in historical accounts', 'Views over Calapan’s eastern coast', 'Local seaside community and picnic setting', 'Nearby Lazareto and Parang coastal areas'],
    operatingHours: 'Current beach access and privately managed facility hours are not confirmed. Plan a daylight visit and ask locally before using beachfront facilities.',
    entranceFee: 'No single current fee is confirmed for the entire Suqui shoreline. Ask your chosen entrance or establishment about admission, cottage rental, parking, and other service charges. Rates in older reviews or a nearby resort listing should not be treated as the beach’s current price.',
    bestTimeToVisit: 'Choose a fair-weather daylight visit, with a cooler morning or late afternoon for walking and photography. Check the tide and beach conditions locally; swimming suitability is not confirmed by this guide.',
    rules: ['Use only authorized shore access; respect private properties.', 'Follow local swimming restrictions and avoid strong currents.', 'Supervise children and keep clear of boat activity.', 'Leave the shoreline clean and do not disturb marine life.'],
    travelTips: ['Choose and confirm a specific access point before leaving; public shore areas and private properties have different arrangements.', 'Ask about current water conditions, lifeguard availability, and permitted activities before entering the sea.', 'Wear footwear for shoreline walks and bring water, sun protection, and a rubbish bag.', 'For a picnic, confirm seating, cottage rental, toilets, and food arrangements with the establishment.', 'Arrange return transport and leave enough daylight for the trip back to Calapan.'],
    nearbyPlaces: ['Calapan Zoological and Recreational Park', 'Silonay Mangrove Conservation Eco-Park', 'Calapan city center'],
    sources: [source('Historical Calapan tourism guide: Lazareto–Suqui–Parang coast', 'https://www.vigattintourism.com/tourism/articles/Welcome-to-Calapan-City'), source('Suqui Beach visitor accounts — historical descriptions, 2014', 'https://www.tripadvisor.com/Attraction_Review-g298447-d3668693-Reviews-Suqui_Beach-Calapan_Oriental_Mindoro_Province_Mindoro.html'), source('Provincial Planning Office: Suqui Beach coastal clean-up record', 'https://ppdo.ormindoro.gov.ph/wp-content/uploads/2022/10/AR-2018.pdf')],
  },
];

export const destinations = entries.map(d => ({
  ...basics, ...d,
  precautionaryMeasures: visitorDetails[d.id].precautions,
  visitorPlanning: visitorDetails[d.id].planning,
  directions: {
    gettingToCalapan,
    ...d.directions,
    faresAndBooking: visitorDetails[d.id].faresAndBooking,
    returnTransport: visitorDetails[d.id].returnTransport,
  },
  tourismAssistance: cityContact,
  emergencyInformation,
  sources: [...d.sources, ...planningSources],
  images: destinationImages[d.slug],
  qrCodeUrl: '/destination/' + d.id,
}));
export const getDestination = key => destinations.find(d => String(d.id) === key || d.slug === key);
export const destinationInformationPath = d => d.qrCodeUrl + '#information';
export const destinationUrl = d => {
  const configured = import.meta.env?.VITE_PUBLIC_SITE_URL;
  const origin = configured || (typeof window !== 'undefined' ? window.location.origin : 'https://example.com');
  return new URL(destinationInformationPath(d), origin).href;
};
