import React,{useEffect,useRef,useState} from 'react';
import {Camera,X,ChevronLeft,ChevronRight,QrCode,MapPin,Download,Printer} from 'lucide-react';
import QRCode from 'qrcode';
import {destinationUrl} from './destinations';
const num=id=>String(id).padStart(2,'0');
export function PhotoGallery({destination:d}){
 const[active,setActive]=useState(null);const dialog=useRef(null),touch=useRef(null);
 useEffect(()=>{if(active!==null&&!dialog.current?.open)dialog.current?.showModal();},[active]);
 const close=()=>{dialog.current?.close();setActive(null);};const next=step=>setActive(i=>(i+step+d.images.length)%d.images.length);
 return <section className="section gallery-section container" id="gallery"><div className="section-heading"><div><p className="eyebrow"><span/>A GLIMPSE OF THE EXPERIENCE</p><h2>Destination <em>Gallery</em></h2><p>{d.slug==='aganhao-islet'?'An aerial view of Aganhao, with closer views of its shoreline and greenery from the same photograph. Tap a view to explore.':d.images.some(img=>img.placeholder)?'Confirmed photos are shown where available; remaining slots are marked Photo coming soon.':'A few perspectives on '+d.name+'. Tap a photo to take a closer look.'}</p></div></div><div className="gallery-grid">{d.images.map((img,i)=><button className="gallery-thumb" key={img.src} onClick={()=>setActive(i)} aria-label={`View photo ${i+1} of ${d.name}`}><img src={img.src} alt={img.alt} loading="lazy"/><span><Camera size={18}/> {img.placeholder?'Photo coming soon':'View photo'}</span></button>)}</div><dialog ref={dialog} className="lightbox" aria-label={`${d.name} photo gallery`} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}} onKeyDown={e=>{if(e.key==='ArrowRight')next(1);if(e.key==='ArrowLeft')next(-1);}}><button className="lightbox-close icon-button" aria-label="Close gallery" onClick={close}><X/></button>{active!==null&&<><div className="lightbox-main" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{const distance=touch.current-e.changedTouches[0].clientX;if(Math.abs(distance)>45)next(distance>0?1:-1);}}><button className="lightbox-prev icon-button" aria-label="Previous photo" onClick={()=>next(-1)}><ChevronLeft/></button><img src={d.images[active].src} alt={d.images[active].alt}/><button className="lightbox-next icon-button" aria-label="Next photo" onClick={()=>next(1)}><ChevronRight/></button></div><p className="lightbox-caption">{d.images[active].alt} <span>{active+1} / {d.images.length}</span></p></>}</dialog></section>;
}
export function QRCodeImage({destination:d}){
 const[src,setSrc]=useState(''),[error,setError]=useState(false);const url=destinationUrl(d);
 useEffect(()=>{let alive=true;QRCode.toDataURL(url,{width:360,margin:3,errorCorrectionLevel:'H',color:{dark:'#30232b',light:'#ffffff'}}).then(value=>{if(alive){setSrc(value);setError(false);}}).catch(()=>{if(alive)setError(true);});return()=>{alive=false;};},[url]);
 if(error)return <p role="alert">The QR code could not be generated. Refresh the page to try again.</p>;
 return src?<img className="qr-image" src={src} alt={`QR code linking directly to ${d.name}`}/>:<div className="qr-loading" role="status">Preparing QR code…</div>;
}
async function downloadQR(d,setError){try{const svg=await QRCode.toString(destinationUrl(d),{type:'svg',width:1000,margin:4,errorCorrectionLevel:'H'});const blob=new Blob([svg],{type:'image/svg+xml'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`sulyap-${num(d.id)}-${d.slug}-qr.svg`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError('The QR download could not be prepared. Please try again.');}}
async function printQR(d,setError){
 let frame;try{const image=await QRCode.toDataURL(destinationUrl(d),{width:900,margin:4,errorCorrectionLevel:'H'});frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:1px;height:1px;bottom:0;left:0;border:0;';frame.title='Printable destination QR code';document.body.appendChild(frame);const doc=frame.contentDocument;doc.open();doc.write('<!doctype html><html><head><title>Sulyap Destination QR code</title><style>body{font-family:Arial,sans-serif;text-align:center;padding:50px;color:#4a3540}img{width:300px;max-width:100%}h1{font-size:28px}small{font-size:18px}</style></head><body></body></html>');doc.close();const heading=doc.createElement('h1');heading.textContent=d.name;const caption=doc.createElement('small');caption.textContent='SCAN TO LEARN MORE · DESTINATION '+num(d.id);const img=doc.createElement('img');img.src=image;img.alt='Destination QR code';doc.body.append(heading,caption,img);await img.decode();frame.contentWindow.addEventListener('afterprint',()=>frame.remove(),{once:true});frame.contentWindow.focus();frame.contentWindow.print();}catch{frame?.remove();setError('Printing could not open. Download the QR code and print the saved file instead.');}
}
export function QRCodeCard({destination:d,compact=false}){const[error,setError]=useState('');return <article className={`qr-card ${compact?'modal-qr-card':''}`}><div className="qr-card-heading"><span>QR CODE {num(d.id)}</span><QrCode size={18}/></div><h3>{d.name}</h3><p className="location-line"><MapPin size={14}/>{d.province}</p><QRCodeImage destination={d}/><p className="scan-label">Scan to Explore</p><div className="qr-tools"><button onClick={()=>downloadQR(d,setError)}><Download size={16}/> Download QR</button><button onClick={()=>printQR(d,setError)}><Printer size={16}/> Print QR</button></div>{error&&<p className="error-message" role="alert">{error}</p>}</article>;}
export function QRModal({destination:d,onClose}){const ref=useRef(null);useEffect(()=>{const node=ref.current;node.showModal();return()=>node.close();},[]);return <dialog ref={ref} className="qr-dialog" aria-label={`QR code for ${d.name}`} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><button className="icon-button modal-close" aria-label="Close QR code" onClick={onClose}><X/></button><QRCodeCard destination={d} compact/></dialog>;}
