import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,Link,NavLink,useLocation,useParams} from 'react-router-dom';
import {MapPin,Compass,QrCode,BookOpen,Route as RouteIcon,Sparkles,Clock,Wallet,Sun,ShieldCheck,Lightbulb,Phone,Hotel,ChevronLeft,ChevronRight,ExternalLink,Smartphone,Leaf,Check,Camera} from 'lucide-react';
import {destinations,getDestination} from './destinations';
import {PhotoGallery,QRCodeImage,QRCodeCard,QRModal} from './features';
import './styles.css';
const sections=[['background','Destination Information','Description & background',BookOpen],['location','Location & Address','Find your place on the map',MapPin],['directions','Transportation & Directions','Routes, fares & return journey',RouteIcon],['thingsToDo','Available Activities','Things to do during your visit',Compass],['attractions','Attractions','The highlights to discover',Sparkles],['operatingHours','Operating Hours','Plan the right time',Clock],['entranceFee','Entrance Fees & Rates','Know before you go',Wallet],['bestTimeToVisit','Best Time to Visit','Find your perfect season',Sun],['rules','Precautions & Rules','Safety & responsible travel',ShieldCheck],['travelTips','Travel Tips','A little local wisdom',Lightbulb],['contactInformation','Contact Details','Destination & tourism assistance',Phone],['nearbyPlaces','Nearby Places','Keep the adventure going',Hotel]];
const num=id=>String(id).padStart(2,'0');
const mapsUrl=d=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(d.name+", Calapan City, Oriental Mindoro")}`;
const directionsUrl=d=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(d.directionsQuery||d.name+", "+d.address)}`;
function updateNavigationOffset(){const height=document.querySelector('.navbar')?.getBoundingClientRect().height||104;document.documentElement.style.setProperty('--navigation-offset',`${height+12}px`);}
function ScrollAndTitle(){const{pathname,hash}=useLocation();useLayoutEffect(()=>{updateNavigationOffset();const match=pathname.match(/^\/destination\/([^/]+)/),d=match&&getDestination(match[1]);const names={'/destinations':'Destinations','/about':'About the Project','/how-it-works':'How It Works','/qr-directory':'QR Code Directory'};document.title=d?`${d.name} — Sulyap`:`${names[pathname]||'Your Calapan Discovery Guide'} — Sulyap`;if(hash)document.getElementById(hash.slice(1))?.scrollIntoView({behavior:hash==='#information'?'instant':'smooth'});else window.scrollTo({top:0,behavior:'instant'});},[pathname,hash]);return null;}
function Logo({light=false}){return <Link to="/" className={`logo ${light?'light':''}`} aria-label="Sulyap home"><span className="brand-artwork"><img src="/branding/sulyap-logo.svg" alt="Sulyap Calapan" width="995" height="1060" decoding="async"/></span></Link>;}
function Navbar(){const[compact,setCompact]=useState(false);const header=useRef(null);useLayoutEffect(()=>{updateNavigationOffset();const observer=new ResizeObserver(updateNavigationOffset);observer.observe(header.current);return()=>observer.disconnect();},[]);useEffect(()=>{const fn=()=>setCompact(window.scrollY>40);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn);},[]);const links=[['/','Home'],['/qr-directory','QR Directory'],['/destinations','Destinations'],['/about','About'],['/how-it-works','How It Works']];return <header ref={header} className={`navbar ${compact?'compact':''}`}><div className="container nav-inner"><Logo/><nav className="nav-links" aria-label="Main navigation">{links.map(([to,label])=><NavLink key={to} to={to} end={to==='/'}>{label}</NavLink>)}</nav><Link className="button small nav-cta" to="/destinations">Explore Destinations</Link></div></header>;}
function Footer(){return <footer><div className="container footer-top"><div className="footer-brand"><p>A little curiosity. A new perspective.<br/>Your next Calapan discovery.</p><span className="footer-motto">Discover. Explore. Experience.</span></div><div><h3>Explore</h3><Link to="/">Home</Link><Link to="/qr-directory">QR Directory</Link><Link to="/destinations">Destinations</Link><Link to="/about">About</Link></div><div><h3>Information</h3><Link to="/destinations">Tourism Guide</Link><Link to="/about#travel-tips">Travel Tips</Link><a href="https://philippines.travel/" target="_blank" rel="noreferrer">Tourism Contact <ExternalLink size={12}/></a></div><div><h3>The Project</h3><Link to="/about">About the Project</Link><Link to="/how-it-works">QR Technology</Link><a href="/photo-credits.html">Photo Credits</a><span className="footer-note"><Leaf size={16}/> Travel gently. Leave only memories.</span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Sulyap. A digital tourism guide.</span><span>Made for discovery. Inspired by Calapan City.</span></div></footer>;}
function Eyebrow({children,light=false}){return <p className={`eyebrow ${light?'on-dark':''}`}><span/>{children}</p>;}
function DestinationCard({destination:d,showQR=false}){const[qr,setQr]=useState(false);return <><article className="destination-card"><Link to={d.qrCodeUrl} className="card-image-link" aria-label={`Explore ${d.name}`}><img src={d.images[0].src} alt={d.images[0].alt} loading="lazy"/><span className="card-number">{num(d.id)}</span><span className="category-chip">{d.category}</span></Link><div className="card-body"><p className="location-line"><MapPin size={14}/>{d.municipality}, {d.province}</p><h3><Link to={d.qrCodeUrl}>{d.name}</Link></h3><p className="card-description">{d.description}</p><div className="card-bottom"><Link to={d.qrCodeUrl} className="text-link">Explore Destination <Compass size={16}/></Link>{showQR&&<button className="icon-button qr-preview-button" title="View QR code" aria-label={`View QR code for ${d.name}`} onClick={()=>setQr(true)}><QrCode size={20}/></button>}</div></div></article>{qr&&<QRModal destination={d} onClose={()=>setQr(false)}/>}</>;}
function SectionHeading({eyebrow,title,description,link}){return <div className="section-heading"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{description&&<p>{description}</p>}</div>{link&&<Link className="button outline" to={link.to}>{link.label}</Link>}</div>;}
function Features(){return <div className="feature-grid">{[[Smartphone,'Easy Access','One scan. Everything you need to discover a destination.'],[MapPin,'Complete Information','Local stories, highlights, and practical details in one place.'],[Compass,'Easy Navigation','Find your way with maps, directions, and useful travel tips.']].map(([Icon,title,text])=><article className="feature" key={title}><span className="feature-icon"><Icon size={25}/></span><h3>{title}</h3><p>{text}</p></article>)}</div>;}
function Steps(){return <div className="steps">{[['Scan','Open your smartphone camera and point it at a destination’s QR code.'],['Explore','Tap the link to open that destination’s guide directly.'],['Discover','Choose a section for stories, maps, activities, and visitor information.']].map(([title,copy],i)=><article key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>;}
function Home(){return <><section className="home-hero"><img className="hero-background" src="/images/baco-island-1.jpg" alt="The wooded Baco island group off the coast of Calapan City" fetchPriority="high"/><div className="hero-shade"/><div className="container hero-content"><Eyebrow light>YOUR CALAPAN DISCOVERY GUIDE</Eyebrow><h1>Discover.<br/>Explore.<br/><em>Experience.</em></h1><p>Discover amazing destinations, explore local attractions, and experience the beauty of our tourist spots through our interactive digital tourism guide.</p><div className="hero-actions"><Link to="/destinations" className="button gold">Explore Destinations <Compass size={18}/></Link><Link to="/about" className="button hero-outline">Discover More</Link></div></div><div className="hero-caption"><MapPin size={16}/><span>Baco Islands, Calapan City<small>A little closer to paradise.</small></span></div><span className="hero-side-label">{destinations.length} DESTINATIONS. ENDLESS DISCOVERY.</span></section></>;}
function PageIntro({eyebrow,title,description}){return <section className="page-intro container"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p>{description}</p></section>;}
function Directory(){return <><PageIntro eyebrow="FIND YOUR NEXT ADVENTURE" title={<>Every place has <em>a story.</em></>} description={`Explore ${destinations.length} selected destinations in Calapan City, Oriental Mindoro. Choose a place and let your curiosity lead the way.`}/><section className="container directory-section"><div className="directory-meta"><span>All destinations <strong>{destinations.length}</strong></span><span><MapPin size={16}/> Across Calapan City</span></div><div className="destination-grid">{destinations.map(d=><DestinationCard key={d.id} destination={d} showQR/>)}</div></section></>;}
function DestinationHero({destination:d}){return <section className={`destination-hero ${d.images[0].placeholder?"photo-pending":""}`}><img className="hero-background" src={d.images[0].src} alt={d.images[0].alt} fetchPriority="high"/><div className="hero-shade"/><div className="container destination-hero-content"><Link className="back-link on-dark" to="/destinations"><ChevronLeft size={17}/> Back to Destinations</Link><Eyebrow light>DESTINATION {num(d.id)} · {d.category}</Eyebrow><h1>{d.name}</h1>{d.images[0].placeholder&&<p className="photo-status">Destination photo coming soon</p>}<p className="hero-location"><MapPin size={18}/>{d.municipality}, {d.province}</p><p className="destination-hero-description">{d.description}</p><a href="#information" className="button gold">Explore Information <Compass size={18}/></a></div></section>;}
function MapSection({destination:d}){
 const hasPin=Number.isFinite(d.latitude)&&Number.isFinite(d.longitude);
 const latitude=hasPin?d.latitude:13.4147,longitude=hasPin?d.longitude:121.1803;
 const box=[longitude-.035,latitude-.025,longitude+.035,latitude+.025].join(',');
 const src=`https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(box)}&layer=mapnik${hasPin?`&marker=${d.latitude},${d.longitude}`:''}`;
 return <div className="map-section"><div className="address-panel"><MapPin/><div><h3>{d.name}</h3><p>{d.address}</p><dl className="coordinates"><div><dt>Municipality</dt><dd>{d.municipality}</dd></div><div><dt>Province</dt><dd>{d.province}</dd></div><div><dt>Coordinates</dt><dd>{hasPin?`${d.latitude.toFixed(4)}, ${d.longitude.toFixed(4)}`:'Exact pin awaiting verification'}</dd></div></dl><p className="small-copy">{d.mapNote}</p></div></div><iframe title={`Map of ${d.name}`} src={src} loading="lazy" referrerPolicy="no-referrer"/><a className="button" href={mapsUrl(d)} target="_blank" rel="noreferrer">Open in Google Maps <ExternalLink size={16}/></a></div>;
}
function InformationCard({section,destination:d}){const[key,title,subtitle,Icon]=section;return <Link className="information-card" to={`${d.qrCodeUrl}/${key}`}><span className="info-icon"><Icon size={23}/></span><div><h3>{title}</h3><p>{subtitle}</p></div><ChevronRight size={18} className="info-chevron"/></Link>;}
function TravelTips({destination:d}){return <section className="container tips-section" id="travel-tips"><div><Eyebrow>A LITTLE PREPARATION GOES A LONG WAY</Eyebrow><h2>Travel well.<br/><em>Explore gently.</em></h2></div><div className="tips-list">{d.travelTips.map(t=><p key={t}><span><Check size={16}/></span>{t}</p>)}</div></section>;}
function MoreDestinations({destination:d}){return <section className="section container"><SectionHeading eyebrow="THE JOURNEY DOESN’T END HERE" title={<>Want to <em>Explore More?</em></>} link={{to:'/destinations',label:'All Destinations'}}/><div className="destination-grid">{destinations.filter(x=>x.id!==d.id).slice(0,3).map(x=><DestinationCard key={x.id} destination={x}/>)}</div></section>;}
function DestinationPage(){const{id}=useParams();const d=getDestination(id);const[qr,setQr]=useState(false);if(!d)return <NotFound/>;return <><DestinationHero destination={d}/><section className="container section destination-info" id="information"><SectionHeading eyebrow="MAKE YOURSELF AT HOME" title={<>Explore This <em>Destination</em></>} description="Choose what you’d like to discover. The details are just a tap away."/><div className="destination-info-layout"><div className="information-grid">{sections.map(s=><InformationCard key={s[0]} section={s} destination={d}/>)}</div><aside className="visitor-note"><span className="note-icon"><Compass size={28}/></span><h3>Your journey,<br/>at a glance.</h3><p><MapPin size={18}/>{d.municipality}, {d.province}</p><p><Sun size={18}/>{d.category}</p><a href={directionsUrl(d)} className="button" target="_blank" rel="noreferrer">{d.directionsQuery?"Find Tourism Office":"Get Directions"} <ExternalLink size={16}/></a><Link className="button outline" to={d.qrCodeUrl+'#gallery'}><Camera size={17}/> View Gallery</Link><button className="button outline" onClick={()=>setQr(true)}><QrCode size={17}/> View Destination QR</button><small>Save a little time for an unexpected discovery.</small></aside></div></section><PhotoGallery destination={d}/><TravelTips destination={d}/><MoreDestinations destination={d}/>{qr&&<QRModal destination={d} onClose={()=>setQr(false)}/>}</>;}
const directionLabels={gettingToCalapan:'Getting to Calapan',startingPoint:'Starting Point',transportation:'Transportation Options',travelTime:'Local Travel Time',route:'Route',landmarks:'Landmarks',publicTransport:'Public Transportation',privateVehicle:'Private Vehicle',faresAndBooking:'Fares & Booking',returnTransport:'Return Journey'};
const planningLabels={facilities:'Facilities to Confirm',accessibility:'Accessibility',preparation:'What to Bring',groupVisits:'Group Visits'};
function DetailList({items}){return <ul className="detail-list">{items.map((item,i)=><li key={item}><span>{num(i+1)}</span>{item}</li>)}</ul>;}
function ContactDetails({contact}){return <div className="contact-details"><h2>{contact.office}</h2><dl className="directions-list">{contact.phone&&<div><dt>Telephone</dt><dd><a href={'tel:'+contact.phone.replace(/[^\d+]/g,'')}>{contact.phone}</a></dd></div>}{contact.email&&<div><dt>Email</dt><dd><a href={'mailto:'+contact.email}>{contact.email}</a></dd></div>}{contact.address&&<div><dt>Office Address</dt><dd>{contact.address}</dd></div>}{contact.officeHours&&<div><dt>Office Hours</dt><dd>{contact.officeHours}</dd></div>}</dl>{contact.socialMedia&&<p><a href={contact.socialMedia} target="_blank" rel="noreferrer">Local tourism social page <ExternalLink size={14}/></a></p>}{contact.website&&<a className="button outline" href={contact.website} target="_blank" rel="noreferrer">View Tourism Listing <ExternalLink size={16}/></a>}</div>;}
function EmergencyHelp({information}){return <aside className="practical-info emergency-help" aria-label="Emergency assistance"><h2><Phone size={21}/> Emergency Assistance</h2><p>{information.description}</p><a className="button outline" href={'tel:'+information.phone}>Call {information.phone}</a><a className="text-link" href={information.source.url} target="_blank" rel="noreferrer">{information.source.title} <ExternalLink size={13}/></a></aside>;}
function InformationSection(){
 const{id,section}=useParams();
 const d=getDestination(id),s=sections.find(x=>x[0]===section);
 if(!d||!s)return <NotFound/>;
 const[,title,,Icon]=s,content=d[section];
 return <div className="container info-detail">
  <Link to={d.qrCodeUrl+'#information'} className="back-link"><ChevronLeft size={17}/> Back to Destination</Link>
  <div className="detail-heading"><span className="feature-icon"><Icon size={26}/></span><div><Eyebrow>{d.name} · DESTINATION {num(d.id)}</Eyebrow><h1>{title}</h1></div></div>
  <div className="detail-layout"><article className="detail-content">
   {section==='location'?<MapSection destination={d}/>:
    section==='background'?<><p className="detail-prose destination-summary">{d.description}</p><h2>About the Destination</h2>{content.split(/\n\s*\n/).map((paragraph,i)=><p className="detail-prose" key={i}>{paragraph}</p>)}<Link className="button outline" to={d.qrCodeUrl+'#gallery'}><Camera size={17}/> View Destination Gallery</Link></>:
    section==='directions'?<><dl className="directions-list">{Object.entries(content).map(([key,value])=><div key={key}><dt>{directionLabels[key]||key}</dt><dd>{value}</dd></div>)}</dl><p className="small-copy">Journey times are planning estimates. Confirm current schedules, fares, the entrance or boat meeting point, and your return arrangements before departure.</p><a href={directionsUrl(d)} className="button" target="_blank" rel="noreferrer">{d.directionsQuery?"Find Tourism Office":"Get Google Maps Directions"} <ExternalLink size={16}/></a></>:
    section==='rules'?<><h2>Precautionary Measures</h2><p className="small-copy">Practical precautions for planning your visit; follow current instructions from site staff and local operators.</p><DetailList items={d.precautionaryMeasures}/><h2 className="detail-subheading">Rules & Responsible Travel</h2><DetailList items={content}/><EmergencyHelp information={d.emergencyInformation}/></>:
    section==='contactInformation'?<><p className="small-copy">Contacts are listed in the tourism resources below. Confirm that the number is still in use before arranging your visit.</p><ContactDetails contact={content}/>{content.office!==d.tourismAssistance.office?<section className="practical-info"><p className="eyebrow">LOCAL TRAVEL ASSISTANCE</p><ContactDetails contact={d.tourismAssistance}/></section>:<p className="small-copy">This is a tourism assistance contact, rather than a confirmed on-site operator. Ask the office to connect you with the destination or a currently authorized community host.</p>}<section className="practical-info"><h2>What to Ask Before Visiting</h2><p>Confirm opening hours, admission and activity charges, current access, permits, facilities, and accessibility. For boat or community tours, ask about the operator, passenger limits, meeting point, weather policy, and return journey.</p></section><EmergencyHelp information={d.emergencyInformation}/></>:
    section==='travelTips'?<><DetailList items={content}/><section className="practical-info"><h2>A Little Planning Goes a Long Way</h2><dl className="directions-list">{Object.entries(d.visitorPlanning).map(([key,value])=><div key={key}><dt>{planningLabels[key]||key}</dt><dd>{value}</dd></div>)}</dl></section></>:
    Array.isArray(content)?<DetailList items={content}/>:<p className="detail-prose">{content}</p>}
   {(section==='operatingHours'||section==='entranceFee')&&<section className="practical-info"><h2>Confirm Before You Go</h2><p>{section==='operatingHours'?'Ask about your intended date, last admission, holidays, and any weather or event restrictions. For boat trips, confirm the departure and mainland return time.':'Ask for the total cost, whether charges are per person or per group, what is included, and any booking or cancellation terms. A free-admission listing does not confirm free transport, guides, or rentals.'}</p><Link className="text-link" to={d.qrCodeUrl+'/contactInformation'}>Contact the Destination <ChevronRight size={16}/></Link></section>}
   <div className="sources"><span>Further reading</span>{d.sources.map(source=><a href={source.url} key={source.url} target="_blank" rel="noreferrer">{source.title}<ExternalLink size={13}/></a>)}</div>
   <Link className="button outline" to={d.qrCodeUrl+'#information'}><ChevronLeft size={17}/> Back to Destination</Link>
  </article><aside className="detail-destination-card"><img src={d.images[0].src} alt={d.images[0].alt}/><div><p className="eyebrow">DESTINATION {num(d.id)}</p><h3>{d.name}</h3><p><MapPin size={14}/>{d.municipality}, {d.province}</p><Link className="text-link" to={d.qrCodeUrl}>Explore This Destination <Compass size={16}/></Link></div></aside></div>
 </div>;
}
function QRDirectory(){const local=['localhost','127.0.0.1'].includes(window.location.hostname)&&!import.meta.env.VITE_PUBLIC_SITE_URL;return <><PageIntro eyebrow="SMALL CODE. BIG DISCOVERY." title={<>QR Code <em>Directory</em></>} description="One unique code for every destination. Download, print, and place each code where the journey begins."/>{local&&<div className="container"><p className="local-notice"><Lightbulb size={20}/> These preview codes point to this computer. Set your public website address before printing codes for visitors.</p></div>}<section className="container qr-directory"><div className="qr-directory-intro"><span><ShieldCheck size={18}/> Every code opens its destination directly.</span><Link to="/how-it-works" className="text-link">How does it work?</Link></div><div className="qr-grid">{destinations.map(d=><QRCodeCard destination={d} key={d.id}/>)}</div></section></>;}
function About(){return <><PageIntro eyebrow="THE IDEA BEHIND SULYAP" title={<>Closer to the place.<br/><em>Connected to its story.</em></>} description="A convenient, accessible digital tourism guide for meaningful journeys in Calapan City."/><section className="container about-page"><div className="about-split"><div className="about-photo"><img src="/images/calapan-city-plaza-1.jpg" alt="Calapan City Plaza in Oriental Mindoro" loading="lazy"/></div><div className="about-copy"><h2>Discovery,<br/><em>made accessible.</em></h2><p>This project helps visitors find destination backgrounds, locations, directions, attractions, and practical travel information using their smartphones.</p><p>At a tourist site, a QR code opens that place’s guide immediately. From home, the directory offers a window into the ten selected Calapan destinations.</p><p>Information is a starting point for planning. Check current fees, schedules, permits, and local conditions with the tourism office or your operator.</p><Link className="button" to="/destinations">Explore the Destinations</Link></div></div><Features/></section><TravelTips destination={destinations[0]}/><section className="section container about-end"><Eyebrow>DESIGNED FOR DISCOVERY</Eyebrow><h2>One guide. <em>Many perspectives.</em></h2><p>Built as an academic tourism project, Sulyap combines destination storytelling with a simple scan-to-explore experience. The guide features ten selected destinations in Calapan City, Oriental Mindoro, from cultural landmarks to coastal and conservation sites.</p><Link to="/how-it-works" className="button outline">Explore the QR Experience</Link></section></>;}
function HowItWorks(){return <><PageIntro eyebrow="DISCOVERY, SIMPLIFIED" title={<>Scan. Explore.<br/><em>Experience.</em></>} description="You’re standing somewhere special. Get to know it with one simple scan."/><section className="container how-section"><div className="how-top"><div className="scan-card large"><QRCodeImage destination={destinations[0]}/><span className="scan-label">TRY IT WITH YOUR CAMERA</span><strong>Discover {destinations[0].name}</strong></div><div><Steps/><div className="how-note"><Lightbulb size={22}/><p>No extra app needed. Use your phone’s camera, tap the link, and choose a destination information card. An internet connection is needed to load the guide.</p></div></div></div><div className="how-bottom"><h2>The right place.<br/><em>The right information.</em></h2><p>Each QR code has a unique destination link. You’ll go directly to the place you scanned, then choose its background, map, directions, attractions, visitor information, or gallery.</p><Link className="button" to="/qr-directory"><QrCode size={18}/> View QR Directory</Link></div></section></>;}
function NotFound(){return <section className="container not-found"><Compass size={52}/><Eyebrow>A SMALL DETOUR</Eyebrow><h1>This place isn’t on the map.</h1><p>The destination or information section could not be found.</p><Link className="button" to="/destinations">Explore Destinations</Link></section>;}
function LoadingScreen(){return <div className="startup-screen" role="status" aria-label="Loading Sulyap"><div className="startup-content"><img className="startup-logo" src="/branding/sulyap-logo.svg" alt="Sulyap Calapan" width="995" height="1060" fetchPriority="high"/><div className="startup-progress" aria-hidden="true"><span/></div><span className="startup-message">Discover. Explore. Experience.</span></div></div>;}
function App(){const[loading,setLoading]=useState(true);useEffect(()=>{const timer=window.setTimeout(()=>setLoading(false),4000);return()=>window.clearTimeout(timer);},[]);if(loading)return <LoadingScreen/>;return <BrowserRouter><ScrollAndTitle/><a className="skip-link" href="#main-content">Skip to content</a><Navbar/><main id="main-content"><Routes><Route path="/" element={<Home/>}/><Route path="/destinations" element={<Directory/>}/><Route path="/destination/:id" element={<DestinationPage/>}/><Route path="/destination/:id/:section" element={<InformationSection/>}/><Route path="/about" element={<About/>}/><Route path="/how-it-works" element={<HowItWorks/>}/><Route path="/qr-directory" element={<QRDirectory/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></BrowserRouter>;}
createRoot(document.getElementById('root')).render(<App/>);
